name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deployment
        run: curl --fail --request POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
